### ISSUE TITLE
Default plane.glb has 0 bytes

### ISSUE THREAD

**Issue by AlessandroMulloni** [SceneView/sceneview-android#265]
I think there was an issue committing the plane.glb file to the assets. It has 0 bytes size.

**Comment by sshah10uol** [comment]
Hi, yeah in the Sample project, this is causing a `java.lang.NullPointerException` at ~line174 in `io.github.sceneview.node.VideoNode`
```Kotlin
model = GLBLoader.loadModel(
    sceneView.context,
    glbFileLocation = glbFileLocation
)!!
```

because further on down `nativeAsset ` is coming back as `0` at ~line122 in `com.google.android.filament.gltfio.AssetLoader`
```Java
@Nullable
public FilamentAsset createAsset(@NonNull Buffer buffer) {
    long nativeAsset = nCreateAsset(mNativeObject, buffer, buffer.remaining());
    return nativeAsset != 0 ? new FilamentAsset(mEngine, nativeAsset) : null;
}
```

Please can `plane.glb` be added properly or can you attach/paste the file/contents to this issue thread in the mean time? Thanks :)
