### ISSUE TITLE
How to set Renderable, set Material, apply texture of Nodes

### ISSUE THREAD

**Issue by MukeshBlippar** [SceneView/sceneview-android#272]
### Discussed in https://github.com/SceneView/sceneview-android/discussions/270

<div type='discussions-op-text'>

<sup>Originally posted by **MukeshBlippar** June  8, 2023</sup>
Hi,

I see in SceneView we have ArModelNode, which takes glb as renderable input. But how can I create Basic shapes, apply texture or change material etc.

In old Sceneform we had Material builder & Texture builder to do above all those things. And we can easily set renderable in Node. But how to achieve same in SceneView ?

I have use cases to show image, gif, basic shapes etc in my scene, already I'm using your another Sceneform java library. Planning to migrate.

Would be great if you can share some code sample. And even better if you can add one sample app related tho material & texture. </div>

**Comment by itssidhere** [comment]
Did you find any updates regarding this?

**Comment by ThomasGorisse** [comment]
My personal recommendation would be to use a glTF even for simple shapes.
You should not see a `.glb` as a `.png` or `.jpg` but more as a `.svg` or `.xml`.
Would you programmatically draw an icon (even simple) with a `Canvas` or use a drawable?
It's mostly the same for .glTF. Just don't forget to export the material you really need (or any).
If you don't need a Lit material just use a background instead of a `Principal BSDF`.

You can then do whatever you want on the materials (and apply an external image or video texture) programmatically by setting the
```
modeInstance.materials[0] = ...
```
With Sceneveview 1.0.x you can even directly modify the shapes by accessing the `modelNode.renderableNodes` and changing every child transform or material.
Even glTF lights are available with `modelNode.lightNodes`
