### ISSUE TITLE
Ar faces

### ISSUE THREAD

**Issue by TooLazyy** [SceneView/sceneview-android#299]
Hi
Any sample of how to implement ar faces feature? I.e. load a model, track face, place model on the face.

**Comment by grassydragon** [comment]
Hi!
As far as I remember, neither we've had time to add a sample for Augmented Faces and address any related issues in the library nor anyone else has succeeded in doing that.

**Comment by TooLazyy** [comment]
Yo. Thanks for the answer. An plans to add AR faces support? Or maybe some implementation helps so I do it on my own?

**Comment by Blizl** [comment]
I found one here: https://github.com/SceneView/sceneform-android/tree/master/samples/augmented-faces, but this is from the old sceneform repo. I can try to add a PR for this if there's enough interest.

**Comment by TooLazyy** [comment]
Yeah, I was able to run the old sample, but this lib seem to be not supporting it yet.
Would be very nice to add

**Comment by bankbiz** [comment]
@grassydragon Can you guide me a little bit to finish the implementation an open PR for this feature? Because I already saw the `AugmentedFaceMode` config and `onAugmentedFaceUpdate` property. A guide from you may help me understand the library code base faster.

Thanks.

**Comment by grassydragon** [comment]
Hi @bankbiz!
Have you already started to write your implementation?
There have been previous attempts by other contributors but they haven't been able to work around some issues. I think the ideal way would be to have a tech talk on our Discord server, however, I need to recollect how the Augmented Faces work and what were the encountered issues :sweat_smile:

**Comment by hshapley** [comment]
I have tried to get Augmented Faces working myself. If you copy the AugmentedFaceNode code from Sceneform and make some small fixes, you can get a 3D model to track with the face. The main part that doesn't work is the face **occlusion**, because Sceneform used an old method of building the mesh that doesn't seem to be supported any more. Now that Geometry has been introduced in Sceneview, it should be possible to rebuild that part, although it'll be hard. I was planning to add AugmentedFaces support when I get some free time, but I don't know when that will be. I could at least add a stripped-down AugmentedFaceNode class that only supports the tracking.
Oh, and putting textures on faces also doesn't work, but I never used that so I don't know how to bring it back either.

**Comment by hshapley** [comment]
Post-0.10.0, models are really tiny and/or far away when using face tracking / the front-facing camera, whereas that wasn't a problem before. That'd need to be fixed for augmented faces to be viable.

**Comment by TooLazyy** [comment]
Hi. Any updates on this? Maybe I can help you?
