### ISSUE TITLE
Duplicate classes conflict with TensorFlow due to flatbuffers

### ISSUE THREAD

**Issue by Michael-Kr** [SceneView/sceneview-android#375]
In our project we use TensorFlowLite that depend on `com.google.ar.flatbuffers` via Gradle.
I see that SceneView uses a copy-pasted `flatbuffers` version with some properties exposed from private to protected.
Building SceneView and Tensor is not possible due to Duplicate classes issue that I could not resolve from our project side.

I've managed to resolve it easily inside the code of SceneView just by using AndroidStudio's refactor tool to move `flatbuffers` contents from `com.google` to `ios.github.sceneview`. @ThomasGorisse Sorry to bother you once more, but I am not quite sure if it is a reasonable solution as I do not know what was the original idea behind copying the `flatbuffers` to inside of the project. If my approach is OK, I can open a merge request with the refactoring result.

**Comment by ThomasGorisse** [comment]
Thanks for the feedback.
This part is unfortunalty still needed until `ViewNode`, `PlaneRenderer` and `CollisionSystem` are not moved to Sceneview implementation.
Could you please create a PR with what you made?
Maybe the cleanest way is to put the content of `java/com/google/ar/sceneform` to `java/src/main/java/io/github/sceneview/sceneform` and also add the `java/com/google/flatbuffers` folder in it.
I can publish a release quickly after that.

**Comment by Caulli** [comment]
> In our project we use TensorFlowLite that depend on `com.google.ar.flatbuffers` via Gradle. I see that SceneView uses a copy-pasted `flatbuffers` version with some properties exposed from private to protected. Building SceneView and Tensor is not possible due to Duplicate classes issue that I could not resolve from our project side.
> 
> I've managed to resolve it easily inside the code of SceneView just by using AndroidStudio's refactor tool to move `flatbuffers` contents from `com.google` to `ios.github.sceneview`. @ThomasGorisse Sorry to bother you once more, but I am not quite sure if it is a reasonable solution as I do not know what was the original idea behind copying the `flatbuffers` to inside of the project. If my approach is OK, I can open a merge request with the refactoring result.

Would you mind providing information on how you did this? I'm struggling with the same issue but don't know how the refactor tool works.

**Comment by Michael-Kr** [comment]
@Caulli you can check MR that I opened for this issue: https://github.com/SceneView/sceneview-android/pull/377

**Comment by swichertdev** [comment]
Our team also ran into this issue. In our project `com.google.flatbuffers.*` is already used over another dependency and now we got the same `checkDebugDuplicateClasses` build problem. We want to use your library, because it helps a lot. Thx you in advance.

I have a few questions regarding this issue:

1. @ThomasGorisse could you pls explain what was the reason to copy the `flatbuffers` code in the first place instead of using a dependency to their library? Because this would be the usual way, right?

2. What was the reason this PR was closed: https://github.com/SceneView/sceneview-android/pull/377 ? Because if you don't want to add `flatbuffers` as a dependency you should at least use your own package id for your code in the sceneview library, right?
