### ISSUE TITLE
Detecting vertical walls, dosent work.

### ISSUE THREAD

**Issue by CapelaA10** [SceneView/sceneview-android#54]
Hey. 

Doing the implementation we found out that ARCore whitout sceneview is able to detect vertical walls with just one color.
Like in the example by google hello_ar_java, that is working.

But with sceneview that was not the case. Changing the config from HORIZONTAL_VERTICAL or just VERTICAL in the plane finding mode, doesn't make a difference.

We know that it's possible and we see a lot of "default" implementations of ArCore doing this.
This is an issue? This will be fixed? What can we expect SceneView to do about this?

**Comment by CapelaA10** [comment]
Hey @grassydragon, yes we are using the last java version because of augmented faces support, should this make a difference?

**Comment by hlefe** [comment]
Hello,
Using configureSession after creating ARSceneView doesn't seem to work:

```
sceneview.apply {  
    configureSession { session, config ->  
        config.planeFindingMode = Config.PlaneFindingMode.VERTICAL  
    }  
}
```
(With the code above, ARCore doesn't seem to apply the configuration change.)


➡️ Instead, you need to set Config.PlaneFindingMode.VERTICAL during initialization like this:

```
sessionConfiguration = { session, config ->  
    planeFindingMode = Config.PlaneFindingMode.VERTICAL  
}  
sceneView = ARSceneView(  
    viewContext,  
    sharedLifecycle = lifecycle,  
    sessionConfiguration = { session, config ->  
        config.apply { planeFindingMode = PlaneFindingMode.VERTICAL }  
    }  
)
```
💡 If you want to change the configuration after initialization, you need to do it like this:

```
sceneView.session?.let { session ->  
    session.configure(session.config.apply {  
        planeFindingMode = Config.PlaneFindingMode.VERTICAL  
    })  
}
```
⚠️ And one last thing to make it work: you need to set the planeRendererMode like this (otherwise, vertical planes won't be displayed):

```
sceneView.apply {  
    planeRenderer.isEnabled = argShowPlanes  
    planeRenderer.isVisible = argShowPlanes  
    planeRenderer.planeRendererMode = PlaneRenderer.PlaneRendererMode.RENDER_ALL  
}
```

You can find my complete code here if it might help you:
https://github.com/hlefe/ar_flutter_plugin_flutterflow/blob/sceneview-android/android/src/main/kotlin/io/carius/lars/ar_flutter_plugin_flutterflow/ArView.kt
