### ISSUE TITLE
Model gets really glossy with LightEstimationMode.ENVIRONMENTAL_HDR

### ISSUE THREAD

**Issue by StevenMOG** [SceneView/sceneview-android#67]
With the 0.4.x release the models look very glossy and dark in AR. Using LightEstimationMode.AMBIENT_INTENSITY the model looks like intended.

@ThomasGorisse Do I have to change some settings with the new Environmental HDR code?

**Comment by ThomasGorisse** [comment]
You can have a look at the Filament discussion https://github.com/google/filament/discussions/5416
I have to admit that I'm a little bit lost between applying a specular filter, generating prefilter mipmap, keeping the cubemap from ARCore as it is.
The last option was recently prefered since specular filter is too much consuming for a frame update and the prefilter generates too rough results.
Any help on this would be appreciated.
