### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by zhupengxiang** [SceneView/sceneview-android#77]
gltf file failed to load

/io.github.sceneview.sample.modelviewer E/RenderableInstance: Failed to download data uri https://mdn.alipayobjects.com/rms/afts/file/https://gw.alipayobjects.com/os/H5App-BJ/1651200213519-gltf/scene.bin
    android.os.NetworkOnMainThreadException

this is gltf url: https://mdn.alipayobjects.com/rms/afts/file/A*wQUKSp0j_0oAAAAAAAAAAAAAARQnAQ

**Comment by onuralpszr** [comment]
I tried to download first link which is "broken to me " I can't opened as well ,and second link is just 5kb so your issue not related to sceneview. it is just a problem with your URL and Network, If you have files locally and try to do that first, because this links is are not accessible to me.

Also you merge your bin and gltf files (basically re-save as with embedded binary so you will going to have one file only, you can use "blender" )
