### ISSUE TITLE
Need help regarding Augmented Image

### ISSUE THREAD

**Issue by monsterbrain** [SceneView/sceneview-android#81]
Hi,

   We are planning to move from sceneform android to sceneview and we are primarily focusing on Augmented Images.
   
   Does sceneview has a sample for augmented images ? I found some augmentedImage related code in library code.
   
   How can I go about implementing it ? Where do I start ? Anyway, I'll try implementing it, will let you know if I hit some block somewhere.

**Comment by LukasPoque** [comment]
I was facing the same issue since there is no example code for this library yet. But here are some steps that might help you to start:

Get the `ArScenView` like the other examples show: `ArScenView sceneView = view.findViewById<ArSceneView?>(R.id.sceneView);` Then configure the image database in the `configureSession`-method of the `sceneView` like this:
```kotlin
// in your onViewCreated, after you setup the ArSceneView
sceneView.configureSession(this::initialiseSceneViewSession)

// ---

private fun initialiseSceneViewSession(session: ArSession, config: Config) {
       // other init stuff ....
       // init image database
       val imageDatabase = this.requireActivity().assets.open(TRACKED_IMAGE_DATABASE_PATH).use {
            AugmentedImageDatabase.deserialize(session, it)
        }
        config.augmentedImageDatabase = imageDatabase
        session.configure(config)
    }
````

Now you only need to connect to the `onAugmentedImageUpdate` callback of the `scenView` in order to be notified if an image is tracked. 

```kotlin
// in your onViewCreated, after you configureSession
sceneView.onAugmentedImageUpdate = this::checkAugmentedImageUpdate

// ---

private fun checkAugmentedImageUpdate(augmentedImage: AugmentedImage) {
        Log.i(
            TAG, "Augmented image update ${augmentedImage.name} with " +
                    "tracking state ${augmentedImage.trackingState}"
        )
    }
````

The last important step is to anchor your model node at the center of that image. Therefore you can simply create an anchor from the center pose of the augmented image in the callback:

```kotlin
// in checkAugmentedImageUpdate, modelNode is a simple ArModelNode with an loaded 3d model
val anchorImage = augmentedImage.createAnchor(augmentedImage.centerPose)
modelNode.anchor = anchorImage
sceneView.addChild(modelNode)
````

Hope this helps you to get started :v:

@ThomasGorisse If something here is totally wrong please correct me :)

**Comment by monsterbrain** [comment]
Thanks a lot @LukasPoque .. I'll try it for sure.

**Comment by un-ro** [comment]
Thanks, @LukasPoque, your guide is understandable. 👍

**Comment by hjaeho95** [comment]
How do I modify the "scenview_fit_to_scan" image?

**Comment by ThomasGorisse** [comment]
Override it in the res folder

**Comment by Cardo** [comment]
Hi @LukasPoque, the checkAugmentedImageUpdate function on the example gives me an error of wrong type (as in type mismatch with MutableList<(AugmentedImage -> Unit)> required). Any clue on how this checkAugmentedImageUpdate function should be formed? Thanks in advance.

**Comment by iSTAYERi** [comment]
Hi @Cardo, this code works for me:
```kotlin
sceneView.onAugmentedImageUpdate = mutableListOf(
    { augmentedImage ->
        if (augmentedImage.trackingState == TrackingState.TRACKING) {
            val anchorImage = augmentedImage.createAnchor(augmentedImage.centerPose)
            modelNode!!.anchor = anchorImage
            binding.sceneView.addChild(modelNode!!)
        }
    }
)
```
